#-----------------------------------------------------------------------------
# Name:        RadiCALModels
# Purpose:     To handle output from the radiCAL program written by Nate Orloff
# Author:      Aric Sanders
# Created:     9/8/2016
# License:     MIT License
#-----------------------------------------------------------------------------
""" Handles the data saved after running Radical to analyze data. The assumed
 format is .mat V7.3, if saved in the older format, resave by setting preferences
 in matlab Environment->Preferences->General->MAT-Files->V7.3. This stores the result
 as an hd5 file with a .mat extension. Previous versions of matlab can be handled using
 scipy.io.loadmat, but this module does not use this function"""

#-----------------------------------------------------------------------------
# Standard Imports
import os
import sys
#-----------------------------------------------------------------------------
# Third Party Imports
# magic statement that injects the pyMeasure folder into sys.path
# This allows Code to be imported skipping pyMeasure/.__init__.py
sys.path.append(os.path.join(os.path.dirname( __file__ ), '..','..'))
try:
    from Code.DataHandlers.TouchstoneModels import *
except:
    print("The module pyMeasure.Code.DataHandlers.TouchstoneModels was not found or had an error,"
          "please put it on the python path")
    raise
try:
    import h5py
except:
    print("The module h5py was not found or had an error,"
          "please put it on the python path or resolve the error. (pip install h5py)")
    raise

try:
    import numpy as np
except:
    print("The module numpy was not found or had an error,"
          "please put it on the python path or resolve the error. (pip install numpy)")
    raise
#-----------------------------------------------------------------------------
# Module Constants

#-----------------------------------------------------------------------------
# Module Functions
def radical_dataset_to_s2p(radical_data_set,frequency_list,**options):
    """Takes a radical data set that is of the form <HDF5 dataset "S1": shape (4, 512), type "|V16"> and outputs
    an S2PV1 python model. Requires frequency_list=np.array(radical_data_file["RadiCalData/StatistiCalData/F"])[0].tolist()
    to be passed"""
    defaults={"frequency_selector":0,"frequency_column_name":"Frequency"}
    s2p_options={}
    for key,value in defaults.iteritems():
        s2p_options[key]=value
    for key,value in options.iteritems():
        s2p_options[key]=value
    input_data=np.array(radical_data_set)
    sparameters=[]
    for index,item in enumerate(frequency_list):
        [S11,S21,S12,S22]=[complex(input_data[0][index][0],input_data[0][index][1]),
                           complex(input_data[1][index][0],input_data[1][index][1]),
                           complex(input_data[2][index][0],input_data[2][index][1]),
                           complex(input_data[3][index][0],input_data[3][index][1])]
        new_row=[item,S11,S21,S12,S22]
        sparameters.append(new_row)
    new_s2p=S2PV1(None,sparameter_complex=sparameters,**s2p_options)
    return new_s2p

# Does this belong in HD5Models?
def print_hd5_keys(hd5_group):
    """Prints hd5 keys and passes if there are none"""
    try:
        print hd5_group
    except: pass

def return_hd5_keys(hd5_group):
    """Returns hd5 keys and passes if there are none"""
    keys=[]
    try:
        hd5_group.visit(lambda x:keys.append(x))
    except: pass
    return keys
#-----------------------------------------------------------------------------
# Module Classes
class RadicalDataModel():
    """RadicalDataModel is a container for data generated by the matlab program radical
    copyright 2011, Nathan Orloff. Typically the file is found in Radical_Solutions/RadicalData.mat or renamed"""
    def __init__(self,file_path=None,**options):
        defaults={}
        self.options={}
        for key,value in defaults.iteritems():
            self.options[key]=value
        for key,value in options.iteritems():
            self.options[key]=value
        if file_path is None:
            pass
        else:
            self.data_file=h5py.File(file_path,"r")
            # load the frequency list
            self.frequency_list=np.array(self.data_file["RadiCalData/StatistiCalData/F"])[0].tolist()
            # create some s2p file attributes for easy access
            self.uncorrected_short=radical_dataset_to_s2p(self.data_file["RadiCalData/StatistiCalData/S"],
                                                          self.frequency_list)
            self.uncorrected_Rs=radical_dataset_to_s2p(self.data_file["RadiCalData/StatistiCalData/Rs"],
                                                       self.frequency_list)
            self.corrected_Rs=radical_dataset_to_s2p(self.data_file["RadiCalData/Ref/TRL/Models/Rs"],
                                                       self.frequency_list)
            self.corrected_DUT=radical_dataset_to_s2p(self.data_file[self.data_file[np.array(self.data_file["RadiCalData/Dut/Calibrated"])[0][0]][0][0]],
                      self.frequency_list)
            self.propagation_constant=np.array(self.data_file["RadiCalData/Ref/TRL/PropConst"])
    def show(self):
        """Displays corrected DUT as s2p"""
        self.corrected_DUT.show()
#-----------------------------------------------------------------------------
# Module Scripts

#-----------------------------------------------------------------------------
# Module Runner
if __name__ == '__main__':
    pass